# NumPy Arrays
Before venturing further, let's look into NumPy arrays

In [1]:
import cv2
import numpy as np

In [2]:
img = cv2.imread('images/image1.jpeg')

`img` is a NumPy array like before. Let's print it out.

In [3]:
print(img)

[[[255 243 207]
  [187 159 105]
  [199 164  91]
  ..., 
  [206 164  87]
  [206 164  87]
  [206 164  87]]

 [[255 243 207]
  [187 159 105]
  [199 164  91]
  ..., 
  [206 164  87]
  [206 164  87]
  [206 164  87]]

 [[255 243 207]
  [187 159 105]
  [199 164  91]
  ..., 
  [206 164  87]
  [206 164  87]
  [206 164  87]]

 ..., 
 [[ 51  51  51]
  [ 51  51  51]
  [ 51  51  51]
  ..., 
  [ 51  51  51]
  [ 51  51  51]
  [ 51  51  51]]

 [[ 51  51  51]
  [ 51  51  51]
  [ 51  51  51]
  ..., 
  [ 51  51  51]
  [ 51  51  51]
  [ 51  51  51]]

 [[ 51  51  51]
  [ 51  51  51]
  [ 51  51  51]
  ..., 
  [ 51  51  51]
  [ 51  51  51]
  [ 51  51  51]]]


As you can see, it's a 3D array with a shit ton of numbers.

NumPy arrays have some cool features.

In [4]:
print(img.shape)

(1073, 1280, 3)


We can get the resolution of the image using `shape`

In [5]:
print(img[0])

[[255 243 207]
 [187 159 105]
 [199 164  91]
 ..., 
 [206 164  87]
 [206 164  87]
 [206 164  87]]


In [6]:
print(img[0,0])

[255 243 207]


In [7]:
print(img[0,0,0])

255


In [13]:
print(img[0][0])

[255 243 207]


In [19]:
a = img[0:2,0:2]
print(a)

[[[255 243 207]
  [187 159 105]]

 [[255 243 207]
  [187 159 105]]]


We don't have much time to delve into NumPy arrays, but we'll see its features as and when we use them. 

Here's a link to the full documentation: https://docs.scipy.org/doc/numpy-dev/reference/

# Bonus Question
How would you crop an image into a 1000x1000 image?

Try it below...